version: '3'


services:
  backend:
    build: ./
    container_name: quizer_container
    working_dir: /quizer
    ports:
      - 8010:8000
    volumes:
      - ./src:/quizer/src
      - ./commands:/quizer/commands
    command:
      - ./commands/start_server_dev.sh
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pg_data: { }
  pgadmin_data: { }

